implemented docker images to cicd pipeline

diff --git a/.github/workflows/frontend-template.yml b/.github/workflows/frontend-template.yml
--- a/.github/workflows/frontend-template.yml
+++ b/.github/workflows/frontend-template.yml
@@ -7,51 +7,51 @@ env:
   WORKING_DIR: frontend/hotel-booking-frontend
 
 jobs:
-  lint:
-    name: Lint Frontend Code
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: frontend/hotel-booking-frontend
+  # lint:
+  #   name: Lint Frontend Code
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       working-directory: frontend/hotel-booking-frontend
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
 
-      - name: Install dependencies
-        run: npm install
+  #     - name: Install dependencies
+  #       run: npm install
 
-      - name: Run ESLint and generate report
-        run: |
-          # Run linting, even if there are errors, to generate the report
-          npm run lint -- --format json -o eslint-report.json || true
+  #     - name: Run ESLint and generate report
+  #       run: |
+  #         # Run linting, even if there are errors, to generate the report
+  #         npm run lint -- --format json -o eslint-report.json || true
 
-      - name: Check if ESLint report exists
-        run: |
-          # Confirm if the ESLint report exists
-          ls -alh
-          if [ -f "eslint-report.json" ]; then
-            echo "eslint-report.json found!"
-          else
-            echo "eslint-report.json not found!"
-            exit 1
-          fi
+  #     - name: Check if ESLint report exists
+  #       run: |
+  #         # Confirm if the ESLint report exists
+  #         ls -alh
+  #         if [ -f "eslint-report.json" ]; then
+  #           echo "eslint-report.json found!"
+  #         else
+  #           echo "eslint-report.json not found!"
+  #           exit 1
+  #         fi
 
-      - name: Upload Lint Report as Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: eslint-report
-          path: ./frontend/hotel-booking-frontend/eslint-report.json
+  #     - name: Upload Lint Report as Artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: eslint-report
+  #         path: ./frontend/hotel-booking-frontend/eslint-report.json
 
   build_and_push_docker:
     name: Build & Push Docker Image
     runs-on: ubuntu-latest
-    needs: lint
+    # needs: lint
     defaults:
       run:
         working-directory: frontend/hotel-booking-frontend
